#服务启动端口号
server:
  port: 8080
#服务名称  
spring:
    application:
        name: app-mysite-eureka
#服务ip
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    #是否可以注册到其他注册中心上（集群的时候改为true）
    register-with-eureka: false
    #是否需要从eureka上获取注册信息
    fetch-registry: false
    #服务注册中心的配置内容，指定服务注册中心的位置
    serviceUrl:  
        defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/  
 
